### ISSUE TITLE
Fail with sshkit 1.15.0

### ISSUE THREAD

**Issue by crmaxx** [capistrano-plugins/capistrano-unicorn-nginx#105]
** Invoke unicorn:setup_app_config (first_time)
** Execute unicorn:setup_app_config
  INFO [a30752d8] Running /usr/bin/env mkdir -pv /home/deploy/app/shared/config as deploy@10.211.55.14
 DEBUG [a30752d8] Command: /usr/bin/env mkdir -pv /home/deploy/app/shared/config
  INFO [a30752d8] Finished in 0.040 seconds with exit status 0 (successful).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@10.211.55.14: undefined method `start_with?' for #<Pathname:/home/deploy/app/shared/config/unicorn.rb>
/Users/mzhukov/.rvm/gems/ruby-2.4.2@app/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/mzhukov/.rvm/gems/ruby-2.4.2@app/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'

Caused by:
NoMethodError: undefined method `start_with?' for #<Pathname:/home/deploy/app/shared/config/unicorn.rb>
/Users/mzhukov/.rvm/gems/ruby-2.4.2@app/gems/sshkit-1.15.0/lib/sshkit/backends/netssh.rb:66:in `upload!'
/Users/mzhukov/.rvm/gems/ruby-2.4.2@app/bundler/gems/capistrano-unicorn-nginx-2e7422cc0d40/lib/capistrano/tasks/unicorn.rake:49:in `block (3 levels) in <top (required)>'
/Users/mzhukov/.rvm/gems/ruby-2.4.2@app/gems/sshkit-1.15.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/mzhukov/.rvm/gems/ruby-2.4.2@app/gems/sshkit-1.15.0/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/mzhukov/.rvm/gems/ruby-2.4.2@app/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => unicorn:setup_app_config

**Comment by kruglyjmax** [comment]
Update sshkit gem to 1.15.1 [https://github.com/capistrano/sshkit/issues/409](https://github.com/capistrano/sshkit/issues/409)
